name: matwright_dev
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.14.6 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.1.7
  bloc: ^3.0.0
  flutter_chips_input: 1.9.0-dev.1
  flutter_webview_plugin: 0.3.11
  cloud_firestore: 0.13.4
  webview_flutter: ^0.3.19+8
  flutter_widget_from_html_core: 0.3.2+1
  flutter_form_builder:  ^3.10.1
  flutter_bloc: ^3.2.0
  flutter_localizations:
    sdk: flutter
  intl:
  intl_translation:
  flutter_cupertino_localizations: ^1.0.1
  flutter_spinkit: "^2.1.0"
  carousel_slider: ^1.3.0
  badges: ^1.1.1
  animated_background: ^1.0.5
  flushbar: ^1.9.1
  shared_preferences: ^0.5.4+8
  shared_preferences_web: ^0.1.0
  responsive_builder: ^0.1.2
  flutter_wordpress: ^0.1.4
  url_launcher: ^5.1.4
  url_launcher_web: ^0.1.0
  font_awesome_flutter : ^8.7.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  avatar_glow: ^1.0.0
  flare_flutter:
    git:
                   url: git://github.com/2d-inc/Flare-Flutter.git
                   ref: dev
                   path: flare_flutter
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/terms.en.html
    - assets/legal.en.html
    - assets/terms.fr.html
    - assets/legal.fr.html
    - assets/coder.png
    - assets/logo.png
    - assets/logoWhite.png
    - assets/matwright.jpg
    - assets/flare/mw.flr
    - assets/flare/Coding.flr
    - space.mp3
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
fonts:
  - family: Open Sans
    fonts:
      - asset: assets/fonts/OpenSans-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/OpenSans-Regular.ttf
        weight: 400
  - family: SpecialElite
    fonts:
       - asset: assets/fonts/Special_Elite/SpecialElite-Regular.ttf
  - family: Raleway
    fonts:
       - asset: assets/fonts/Raleway/Raleway-Regular.ttf
       - asset: assets/fonts/Raleway/Raleway-Italic.ttf
         style: italic
  - family: Alatsi
    fonts:
       - asset: assets/fonts/Alatsi/Alatsi-Regular.ttf

  - family: PermanentMarker
    fonts:
       - asset: assets/fonts/PermanentMarker/PermanentMarker-Regular.ttf