/// Flutter icons SocialIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SocialIcons
///      fonts:
///       - asset: fonts/SocialIcons.ttf
///
/// 
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class SocialIcons {
  SocialIcons._();

  static const _kFontFam = 'SocialIcons';

  static const IconData mail = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData twitter = const IconData(0xf099, fontFamily: _kFontFam);
  static const IconData facebook = const IconData(0xf09a, fontFamily: _kFontFam);
  static const IconData github_circled = const IconData(0xf09b, fontFamily: _kFontFam);
  static const IconData gplus_squared = const IconData(0xf0d4, fontFamily: _kFontFam);
  static const IconData gplus = const IconData(0xf0d5, fontFamily: _kFontFam);
  static const IconData mail_alt = const IconData(0xf0e0, fontFamily: _kFontFam);
  static const IconData linkedin = const IconData(0xf0e1, fontFamily: _kFontFam);
  static const IconData github = const IconData(0xf113, fontFamily: _kFontFam);
  static const IconData youtube_squared = const IconData(0xf166, fontFamily: _kFontFam);
  static const IconData youtube = const IconData(0xf167, fontFamily: _kFontFam);
  static const IconData stackoverflow_1 = const IconData(0xf16c, fontFamily: _kFontFam);
  static const IconData bitbucket = const IconData(0xf171, fontFamily: _kFontFam);
  static const IconData bitbucket_squared = const IconData(0xf172, fontFamily: _kFontFam);
  static const IconData tumblr = const IconData(0xf173, fontFamily: _kFontFam);
  static const IconData tumblr_squared = const IconData(0xf174, fontFamily: _kFontFam);
  static const IconData apple = const IconData(0xf179, fontFamily: _kFontFam);
  static const IconData android = const IconData(0xf17b, fontFamily: _kFontFam);
  static const IconData skype = const IconData(0xf17e, fontFamily: _kFontFam);
  static const IconData trello = const IconData(0xf181, fontFamily: _kFontFam);
  static const IconData stackexchange = const IconData(0xf18d, fontFamily: _kFontFam);
  static const IconData vimeo_squared = const IconData(0xf194, fontFamily: _kFontFam);
  static const IconData mail_squared = const IconData(0xf199, fontFamily: _kFontFam);
  static const IconData google = const IconData(0xf1a0, fontFamily: _kFontFam);
  static const IconData reddit = const IconData(0xf1a1, fontFamily: _kFontFam);
  static const IconData reddit_squared = const IconData(0xf1a2, fontFamily: _kFontFam);
  static const IconData delicious = const IconData(0xf1a5, fontFamily: _kFontFam);
  static const IconData behance = const IconData(0xf1b4, fontFamily: _kFontFam);
  static const IconData behance_squared = const IconData(0xf1b5, fontFamily: _kFontFam);
  static const IconData spotify = const IconData(0xf1bc, fontFamily: _kFontFam);
  static const IconData git_squared = const IconData(0xf1d2, fontFamily: _kFontFam);
  static const IconData git = const IconData(0xf1d3, fontFamily: _kFontFam);
  static const IconData facebook_official = const IconData(0xf230, fontFamily: _kFontFam);
  static const IconData vimeo = const IconData(0xf27d, fontFamily: _kFontFam);
  static const IconData snapchat = const IconData(0xf2ab, fontFamily: _kFontFam);
  static const IconData snapchat_ghost = const IconData(0xf2ac, fontFamily: _kFontFam);
  static const IconData snapchat_square = const IconData(0xf2ad, fontFamily: _kFontFam);
  static const IconData google_plus_circle = const IconData(0xf2b3, fontFamily: _kFontFam);
  static const IconData github_squared = const IconData(0xf300, fontFamily: _kFontFam);
  static const IconData twitter_squared = const IconData(0xf304, fontFamily: _kFontFam);
  static const IconData facebook_squared = const IconData(0xf308, fontFamily: _kFontFam);
  static const IconData linkedin_squared = const IconData(0xf30c, fontFamily: _kFontFam);
}
